gvom:
  gvom_ros2:
    ros__parameters:
      odom_frame: "map"
      xy_resolution: 0.40
      z_resolution: 0.4
      width: 512
      height: 64
      buffer_size: 20
      min_point_distance: 4.0
      min_radar_distance: 50.0
      positive_obstacle_threshold: 1.0
      negative_obstacle_threshold: 0.5
      density_threshold: 50
      slope_obsacle_threshold: 5.0
      robot_height: 1.0
      robot_radius: 1.7
      ground_to_lidar_height: 1.0
      freq: 1.0
      xy_eigen_dist: 1
      z_eigen_dist: 1
      radar_positive_obstacle_threshold: 0.50
      radar_ground_density_threshold: 18000
      radar_obs_density_threshold: 24500
